version: 0.2

env:
  parameter-store:
    IMAGE_REPOSITORY_NAME: IMAGE_REPOSITORY_NAME

phases:
  install:
    commands:
      ## 依存パッケージをインストール
      - npm install
  pre_build:
    commands:
      ## ECRにログイン
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)

      ## Dockerイメージのタグとして使用するため、Gitのコミットハッシュを取得
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      ## テスト実行
      - npm test
#cache:
#  paths:
#   - path