site_name: CI/CDハンズオン
nav:
    - アジェンダ: README.md
    - 全体構成: architecture.md
    - 準備: preparation.md
    - 手動デプロイ: manual-deploy.md
    - CodePipelineによるパイプラインの構築: codepipeline.md
    - 自動デプロイ: auto_deploy.md
    - テスト失敗時にデプロイが止まることを確認: stop-when-test-failed.md
    - まとめ: conclusion.md
    - 参考資料: reference.md
    - 補足：環境の削除: delete-environment.md
theme: readthedocs